version: '3'

services:
  strapi:
    image: someshrao007/strapi:latest
    #alpha_test_strapi:latest
    build: .
    container_name: alpha_test_strapi
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: ./data/data.db
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data

