name: Build and Push Docker Image

on:
  # push:
  #   branches: [ main ]  

jobs:
  
  Build-and-Push-to-Docker:
    runs-on: ubuntu-latest
    environment: Somesh_DEV
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/alpha-strapi:latest
